### ISSUE TITLE
json: cannot unmarshal object into Go struct field UploadAPIError.error of type string

### ISSUE THREAD

**Issue by ncw** [dropbox/dropbox-sdk-go-unofficial#44] opened 2018-05-23 14:08 UTC
This error

    json: cannot unmarshal object into Go struct field UploadAPIError.error of type string

Is produced when trying to unmarshal this error message

```
2018/05/21 22:08:08 DEBUG : HTTP/1.1 409 path/malformed_path/
Transfer-Encoding: chunked
Connection: keep-alive
Content-Security-Policy: sandbox allow-forms allow-scripts
Content-Type: application/json
Date: Mon, 21 May 2018 20:08:08 GMT
Server: nginx
X-Dropbox-Request-Id: 4aa21beb57285ee06c448795c5130144
X-Robots-Tag: noindex, nofollow, noimageindex

99
{"error_summary": "path/malformed_path/", "error": {".tag": "path", "reason": {".tag": "malformed_path"}, "upload_session_id": "AAAAAAAAB0BBH11mLUv5Sg"}}
0

```

This is generated by this bit of code

https://github.com/dropbox/dropbox-sdk-go-unofficial/blob/7afa861bfde5a348d765522b303b6fbd9d250155/dropbox/files/client.go#L3502-L3510

So it looks like the type of error being returned doesn't match

```go
//UploadAPIError is an error-wrapper for the upload route
type UploadAPIError struct {
	dropbox.APIError
	EndpointError *UploadError `json:"error"`
}
```

This error was caused by an attempt to upload a file with a path that was too long

```
2018/05/21 22:08:07 DEBUG : POST /2/files/upload HTTP/1.1
```

**Comment by cs-tejas-mulay** [comment] 2019-05-22 14:43
Hi @ncw ,
I am getting "Error: json: cannot unmarshal object into Go value of type string" even if file name is not long. Filename is just 15 chars long.
I am using latest version of dbxcli:
{MacBook-Pro-4.local}/Users/build$ ./dbxcli-darwin-amd64 version
dbxcli version: v3.0.0
SDK version: 5.4.0
Spec version: 097e9ba

**Comment by ncw** [comment] 2019-05-22 16:31
> I am getting "Error: json: cannot unmarshal object into Go value of type string" even if file name is not long. Filename is just 15 chars long. I have not provided absolute path too.

Can you dump the failing HTTP transaction - then we can see if this is related to this issue or not.

**Comment by cs-tejas-mulay** [comment] 2019-05-31 07:43
Thanks @ncw .
Can you let me know how to get failing HTTP transaction? Is there any flag to show debug output on screen? Could not find any in help.

**Comment by ncw** [comment] 2019-06-03 16:43
> Can you let me know how to get failing HTTP transaction? Is there any flag to show debug output on screen? Could not find any in help.

You can get the requests if you set the log level to Debug.  Not sure how to do this with dbxcli though - you might have to patch the code.

**Comment by ncw** [comment] 2019-06-13 09:27
This is really easy to replicate with this

    rclone mkdir dropbox:"trailing space dir " -vv --dump bodies --retries 1 --low-level-retries 1

```
2019/06/13 10:23:52 DEBUG : HTTP REQUEST (req 0xc000561000)
2019/06/13 10:23:52 DEBUG : POST /2/files/get_metadata HTTP/1.1
Host: api.dropboxapi.com
User-Agent: rclone/v1.47.0-121-g4d195d5a-beta
Content-Length: 126
Authorization: XXXX
Content-Type: application/json
Accept-Encoding: gzip

{"path":"/trailing space dir ","include_media_info":false,"include_deleted":false,"include_has_explicit_shared_members":false}
```

```
2019/06/13 10:23:53 DEBUG : HTTP RESPONSE (req 0xc000561000)
2019/06/13 10:23:53 DEBUG : HTTP/1.1 409 Conflict
Transfer-Encoding: chunked
Connection: keep-alive
Content-Disposition: attachment; filename='error'
Content-Security-Policy: sandbox; frame-ancestors 'none'
Content-Type: application/json
Date: Thu, 13 Jun 2019 09:23:53 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Dropbox-Request-Id: 60eca1971fbb467ac93351e95e117cf0
X-Frame-Options: DENY

6b
{"error_summary": "path/malformed_path/...", "error": {".tag": "path", "path": {".tag": "malformed_path"}}}
0
```

@diwakergupta I'd send a patch but I'm not sure exactly what the error type should be.

**Comment by aaronstaley** [comment] 2019-10-24 18:50
This should be fixed by #53. Is the issue resolved?

**Comment by ncw** [comment] 2019-10-25 13:34
@aaronstaley I can confirm the issue is fixed - thank you :-)

As soon as this hits an official release I'll pull it into rclone.

Thank you :-)

**Comment by KarandeepJohar** [comment] 2020-02-06 03:32
@ncw I'm closing this as it looks like the issue is fixed!

**Closed by KarandeepJohar** 2020-02-06 03:32 UTC
